NUMPY ARE FAST 

IT USES FIXED TYPES
When an Element is created NUMPY assigns it to a fixed type. 

Where Lists depends on the type of data you are working with.

NumPy Uses Less bytes of memory.
There is no type checking as well in NumPy.

Applications of NumPy:

    Mathematics(MATLAB Replacement)
    Plotting(MatplotLib)
    Backend(Pandas,Connect,Digital Photography)


In [8]:
import numpy as np

In [9]:
a = np.array([1,2,3])
print(a) #1-d array

[1 2 3]


In [10]:
b= np.array([[1,2,3],[4,5,6]])
print(b) #2-d array

[[1 2 3]
 [4 5 6]]


In [12]:
# Get Dimension
a.ndim

1

In [13]:
#get shape
a.shape

(3,)

In [15]:
b.shape

(2, 3)

In [16]:
#get type
a.dtype

dtype('int64')

In [20]:
#specify type
a = np.array([1,2,3], dtype='int16')
print(a.dtype)

int16


In [21]:
#get item size
a.itemsize

2

In [23]:
#get total size
a.size * a.itemsize

6

In [27]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
#get a specific element [r,c]
a[1,5]

np.int64(13)

In [29]:
#get a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [31]:
#specific column
print(a[:,2])

[ 3 10]


In [33]:
#startindex:endindex:stepsize
print(a[0,1:6:2])

[2 4 6]


In [34]:
#manipulating array
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [35]:
a[:,2] = 5

In [36]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [37]:
a[1,:]  = 2
print(a)

[[1 2 5 4 5 6 7]
 [2 2 2 2 2 2 2]]


In [39]:
#work outside in
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b[0,1,1]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


np.int64(4)

In [40]:
#replace
b[:,1,:] = [[9,9],[8,8]]

In [41]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [42]:
#all 0s matrix
np.zeros((2,3))
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [44]:
#ones matrix
np.ones((4,2), dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [45]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [47]:
np.full_like(a, 4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.random.rand((4,2)*100)

array([[0.32257279, 0.29017817],
       [0.15988329, 0.97077891],
       [0.42800024, 0.07723503],
       [0.42033811, 0.07656339]])